### ISSUE TITLE
To support multiple tags for a post

### ISSUE THREAD

**Issue by viggy28** [senorprogrammer/til#32]
This is more of a clarification (since I didn't find a suitable group creating this under Feature request).

I couldn't get a post published under multiple tags. Does the project support or am I missing it? (I tried pushing posts with tags separated by whitespace or comma as delimiter, didn't help)

Thanks.

**Comment by senorprogrammer** [comment]
It should work. In the header, for the `tags` key, separate them by a comma. See this example for details: https://raw.githubusercontent.com/senorprogrammer/books/main/docs/2021-05-10T21-43-13-rogue-protocol.md

If that doesn't work for you, let me know here.

**Comment by viggy28** [comment]
Sorry about the delay @senorprogrammer.

Did confirm that it's working as expected. My bad didn't check that twice.
